export const data = [
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000059920400',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000155748400',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000155748500',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000193968400',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000197381200',
      proc_date: 'W2022-08-23',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-19',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000193516500',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000193629400',
      proc_date: 'W2022-08-30',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000207874100',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000219269100',
      proc_date: 'W2022-06-28',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000218066900',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000169983700',
      proc_date: 'W2022-06-07',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-27',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000204638200',
      proc_date: 'W2022-08-09',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000211507500',
      proc_date: 'W2022-08-23',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-16',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000202461500',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-07',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000202881800',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000194992800',
      proc_date: 'W2022-06-28',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-27',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000196355400',
      proc_date: 'W2022-10-11',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-14',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206579900',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-24',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206581000',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206949900',
      proc_date: 'W2022-08-23',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-09',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000207396100',
      proc_date: 'W2022-10-11',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-19',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000211636300',
      proc_date: 'W2022-09-27',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000219539000',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206308000',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000212224300',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209010400',
      proc_date: 'W2022-06-28',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-03',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000218630100',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-15',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000220317200',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-15',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000190321800',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-10-03',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000190520900',
      proc_date: 'W2022-07-12',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-06',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000124029900',
      proc_date: 'W2022-09-27',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-23',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000034261500',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-19',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000192507700',
      proc_date: 'W2022-08-30',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-04',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000203099900',
      proc_date: 'W2022-09-27',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-07',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000200832400',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-28',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000207874000',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000218822300',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000215088600',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000215725300',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000166389400',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-11',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209983000',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-27',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000124607700',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-17',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000155748300',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209092200',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000155748600',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000213073600',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000215848900',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000214654900',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000218068800',
      proc_date: 'W2022-06-07',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-02',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000203879900',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-07',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000203933200',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-20',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000208505400',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-26',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000212217800',
      proc_date: 'W2022-06-07',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000215725500',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209677000',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000219114400',
      proc_date: 'W2022-07-12',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-07',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000124030000',
      proc_date: 'W2022-08-30',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-23',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000198242500',
      proc_date: 'W2022-08-23',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-20',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000198536900',
      proc_date: 'W2022-08-09',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-30',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000203128200',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-11',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000202002900',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-05',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000212810700',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209144700',
      proc_date: 'W2022-07-05',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-24',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000215725400',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000217636000',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000219279000',
      proc_date: 'W2022-06-28',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000219509100',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000194730800',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-17',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000210682300',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206497200',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-15',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000214026500',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000214507000',
      proc_date: 'W2022-09-06',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000194325300',
      proc_date: 'W2022-08-02',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A:',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000197290200',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000202615900',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000204919000',
      proc_date: 'W2022-08-02',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-05-30',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206759100',
      proc_date: 'W2022-10-11',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-04',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000210983100',
      proc_date: 'W2022-09-27',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000193544100',
      proc_date: 'W2022-09-20',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000194787200',
      proc_date: 'W2022-08-09',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000198550500',
      proc_date: 'W2022-06-28',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-03',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000200723200',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-12',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000203011600',
      proc_date: 'W2022-09-27',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000201335100',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-28',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000202616000',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000206767100',
      proc_date: 'W2022-09-06',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-22',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000209955200',
      proc_date: 'W2022-08-16',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000217635900',
      proc_date: 'W2022-07-19',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000218956600',
      proc_date: 'W2022-06-21',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-14',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000211932800',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-07-13',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000196842900',
      proc_date: 'W2022-08-09',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-24',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000199906500',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-29',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000201975900',
      proc_date: 'W2022-08-30',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-25',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 9.406873,
    _source: {
      st13applicationnumber: '300000210485000',
      proc_date: 'W2022-10-04',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-28',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De:   To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000069466800',
      proc_date: 'W2022-10-18',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-30',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 26 To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000192966500',
      proc_date: 'W2022-07-05',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-08',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 130 To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000126967300',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-02',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 5793 To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000161359500',
      proc_date: 'W2022-06-07',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-06-03',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A: 1659',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000210167300',
      proc_date: 'W2022-08-23',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-17',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 4779 To/A: 16080',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 8.910753,
    _source: {
      st13applicationnumber: '300000067602500',
      proc_date: 'W2022-09-06',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-08-31',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext: 'From/De: 16080 To/A: 4779',
    },
  },
  {
    _index: 'cipo-ca_tm_mark_event',
    _score: 6.598172,
    _source: {
      st13applicationnumber: '300000126967300',
      proc_date: 'W2022-09-13',
      markeventcategory: 'National prosecution history entry',
      markeventdate: '2022-09-07',
      markeventcode: 48,
      markeventresponsedate: '-',
      markeventdescriptiontext: 'Agent Changed',
      markeventdescriptiontext_fr: "Changement d'agent",
      markeventadditionaltext:
        'From:       To: 16080  /  Voir Preuve au dossier/See evidence on File No. 1269673',
    },
  },
];
